### ISSUE TITLE
Open Source License details missing

### ISSUE THREAD

**Issue by exequielrafaela** [rog2/certbot-lambda#1]
### What?
Since this is a public repo we assume that the code here is intended to be shared under an Open Source License. So we would like to kindly ask if there is any selected open source license for this repo. 

**Egs:**
* **MIT:** https://github.com/binbashar/terraform-aws-waf-owasp/blob/master/LICENSE.md ( https://choosealicense.com/licenses/mit/)
* **Apache-2.0:** https://choosealicense.com/licenses/apache-2.0/
* **More:** https://choosealicense.com/licenses/

### Why?
* An open source license protects contributors and users. Businesses and savvy developers won’t touch a project without this protection.
* We've rising a related issue in very recently shared public repo in our Github organization: https://github.com/binbashar/terraform-aws-certbot-lambda/issues/1 

Thanks in advance for your contribution here! 

CC: @diego-ojeda-binbash @marceloberesvil

**Comment by zhiguangwang** [comment]
Hi, thanks for the notice.

[MIT License](https://github.com/rog2/certbot-lambda/blob/master/LICENSE.md) has been added to this repo, feel free to use these code :)

**Comment by exequielrafaela** [comment]
Thanks for your quick response and collab here! Much appreciated!
